

import CSVmerger2 from "@/components/csvmerger2";
import { BackgroundRippleEffect } from "@/components/ui/background-ripple-effect";
import { TextAnimate } from "@/components/ui/text-animate";

export const metadata = {
  title: 'CSV merger Free tool',
  description: 'Generated by Maxime Daon',
}

export default function Page() {
  return (
    <> 
    <main>
      <section className="section-lg max-w-screen overflow-hidden relative">
          <BackgroundRippleEffect />
          <div className="relative container-layout z-50 max-w-[85svw] flex flex-col justify-center gap-8 items-center py-10">
            <TextAnimate className="text-center" animation="blurIn" as="h1">
            CSV Merge & Clean
            </TextAnimate>
            <TextAnimate className="text-center w-[60%]" animation="blurIn" as="p">
            Drop your messy CSV exports — get back one clean, deduplicated file. No signup, 100% local.
            </TextAnimate>
            <CSVmerger2 />
            
          </div>  
      </section>
    </main>
      
      
    </>
  );
}
